-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 20:17:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supermarkBaseDatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supermarkBaseDatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supermarkBaseDatos` DEFAULT CHARACTER SET utf8mb4 ;
USE `supermarkBaseDatos` ;

-- -----------------------------------------------------
-- Table `supermarkBaseDatos`.`Usuairo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermarkBaseDatos`.`Usuairo` (
  `idUsuairo` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `permisos` TINYINT NULL,
  PRIMARY KEY (`idUsuairo`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermarkBaseDatos`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermarkBaseDatos`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'Sin nombre',
  `apellido` VARCHAR(45) NOT NULL DEFAULT 'sin apellido',
  `dni` INT NOT NULL,
  `domicilio` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `pais` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `codigoPostal` INT NULL,
  `Usuairo_idUsuairo` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Usuairo_idUsuairo`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_Cliente_Usuairo_idx` (`Usuairo_idUsuairo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Usuairo`
    FOREIGN KEY (`Usuairo_idUsuairo`)
    REFERENCES `supermarkBaseDatos`.`Usuairo` (`idUsuairo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermarkBaseDatos`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermarkBaseDatos`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 0,
  `precioUnitario` FLOAT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT 'sin decsripcion',
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermarkBaseDatos`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermarkBaseDatos`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `Usuairo_idUsuairo` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`, `Usuairo_idUsuairo`),
  INDEX `fk_Administrador_Usuairo1_idx` (`Usuairo_idUsuairo` ASC) VISIBLE,
  INDEX `fk_Administrador_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Usuairo1`
    FOREIGN KEY (`Usuairo_idUsuairo`)
    REFERENCES `supermarkBaseDatos`.`Usuairo` (`idUsuairo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Administrador_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `supermarkBaseDatos`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supermarkBaseDatos`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supermarkBaseDatos`.`Ticket` (
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Usuairo_idUsuairo` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Cliente_Usuairo_idUsuairo`, `Producto_idProducto`),
  INDEX `fk_Cliente_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Producto_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Usuairo_idUsuairo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Producto_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Usuairo_idUsuairo`)
    REFERENCES `supermarkBaseDatos`.`Cliente` (`idCliente` , `Usuairo_idUsuairo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `supermarkBaseDatos`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
